title: "bitesize AIQ"
description: >-
  Helping everyone increase their artificial intelligence IQ, one bite at a time.
  Discover the latest AI tools, concepts, and applications with easy-to-digest guides.
url: "https://bitesize-aiq.github.io"
baseurl: ""

# Social media profiles
twitter_username: bitesize_aiq
github_username: bitesize-aiq
instagram_username: bitesize_aiq
# linkedin_username: company/bitesizeaiq

# Build settings
markdown: kramdown
theme: minima
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Author information
author:
  name: "bitesize AIQ"
  bio: "We're passionate about making AI accessible to everyone through bite-sized insights on the latest AI tools and technologies."
  email: "bitesize.aiq@gmail.com"
  twitter: "bitesize_aiq"

# Pagination
paginate: 9
paginate_path: "/page/:num/"

# Collections
collections:
  categories:
    output: true
    permalink: /category/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AIQ Team"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
